# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 16:50
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_auto_20170806_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True),
        ),
    ]
