# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '__first__'),
        ('trombi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique_assoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default=datetime.datetime.now)),
                ('date_fin', models.DateField(default=datetime.datetime.now)),
                ('role', models.CharField(blank=True, default='', max_length=128)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='association.Association')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='solde_mediamines',
            field=models.FloatField(default=0, verbose_name='solde médiamine'),
        ),
        migrations.AddField(
            model_name='historique_assoc',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trombi.UserProfile'),
        ),
    ]
