# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 21:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trombi', '0002_auto_20170725_1940'),
        ('mediamines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500)),
                ('sommeDebitee', models.FloatField(default=0)),
                ('date', models.DateField(default=datetime.datetime(2017, 7, 26, 21, 24, 1, 794653))),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='trombi.UserProfile')),
                ('mediamine_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediamine_user', to='trombi.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='RecapitulatifImpressions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateGeneration', models.DateField(default=datetime.datetime(2017, 7, 26, 21, 24, 1, 796739))),
                ('zipPhotos', models.FileField(blank=True, null=True, upload_to='')),
                ('zipMiniatures', models.FileField(blank=True, null=True, upload_to='')),
                ('hasDebited', models.BooleanField(default=False)),
                ('isCanceled', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='demandeimpression',
            name='quantite',
        ),
        migrations.AddField(
            model_name='photo',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to='trombi.UserProfile'),
        ),
        migrations.AlterField(
            model_name='appreciationphoto',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 26, 21, 24, 1, 795318)),
        ),
        migrations.AlterField(
            model_name='demandeimpression',
            name='dateDemande',
            field=models.DateField(default=datetime.datetime(2017, 7, 26, 21, 24, 1, 795887)),
        ),
        migrations.AlterField(
            model_name='gallerie',
            name='dateCreation',
            field=models.DateField(default=datetime.datetime(2017, 7, 26, 21, 24, 1, 792064)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='dateUpload',
            field=models.DateField(default=datetime.datetime(2017, 7, 26, 21, 24, 1, 792865)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='identifications',
            field=models.ManyToManyField(blank=True, null=True, related_name='identifications', to='trombi.UserProfile'),
        ),
        migrations.AddField(
            model_name='recapitulatifimpressions',
            name='demandes',
            field=models.ManyToManyField(blank=True, null=True, to='mediamines.DemandeImpression'),
        ),
        migrations.AddField(
            model_name='recapitulatifimpressions',
            name='mediamine_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trombi.UserProfile'),
        ),
    ]
