# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 23:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mediamines', '0003_auto_20170726_2134'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='demandeimpression',
            managers=[
                ('getEnAttente', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='appreciationphoto',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 26, 23, 35, 11, 165330)),
        ),
        migrations.AlterField(
            model_name='demandeimpression',
            name='dateDemande',
            field=models.DateField(default=datetime.datetime(2017, 7, 26, 23, 35, 11, 166302)),
        ),
        migrations.AlterField(
            model_name='gallerie',
            name='dateCreation',
            field=models.DateField(default=datetime.datetime(2017, 7, 26, 23, 35, 11, 160291)),
        ),
        migrations.AlterField(
            model_name='historiqueactions',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 26, 23, 35, 11, 164255)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='dateUpload',
            field=models.DateField(default=datetime.datetime(2017, 7, 26, 23, 35, 11, 161580)),
        ),
        migrations.AlterField(
            model_name='recapitulatifimpressions',
            name='dateGeneration',
            field=models.DateField(default=datetime.datetime(2017, 7, 26, 23, 35, 11, 167509)),
        ),
    ]
