# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 10:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamines', '0010_auto_20170808_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerie',
            options={'permissions': (('gestion_gallerie', 'Peut administrer les galleries'),)},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'permissions': (('gestion_photo', 'Peut administrer les photos'),)},
        ),
        migrations.AlterModelOptions(
            name='recapitulatifimpressions',
            options={'permissions': (('gestion_recap', 'Peut administrer les recaps & les soldes'),)},
        ),
        migrations.AlterField(
            model_name='appreciationphoto',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 8, 10, 30, 10, 4652)),
        ),
        migrations.AlterField(
            model_name='demandeimpression',
            name='dateDemande',
            field=models.DateField(default=datetime.datetime(2017, 8, 8, 10, 30, 10, 5295)),
        ),
        migrations.AlterField(
            model_name='gallerie',
            name='dateCreation',
            field=models.DateField(default=datetime.datetime(2017, 8, 8, 10, 30, 10, 695)),
        ),
        migrations.AlterField(
            model_name='historiqueactions',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 8, 10, 30, 10, 3879)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='dateUpload',
            field=models.DateField(default=datetime.datetime(2017, 8, 8, 10, 30, 10, 1731)),
        ),
        migrations.AlterField(
            model_name='recapitulatifimpressions',
            name='dateGeneration',
            field=models.DateField(default=datetime.datetime(2017, 8, 8, 10, 30, 10, 6181)),
        ),
    ]
